IBay/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', TemplateView.as_view(template_name='account/login.html'), name='home'),
    path('accounts/', include('allauth.urls')),
    path('',include('Stores.urls',namespace='Stores')),     
    path('location/',include('Location.urls')),
    path('user/', include('UserApp.urls')),
    path('product/',include('Products.urls')),
    path('order/', include('OrderApp.urls',namespace='OrderApp')),
    
    
    
    
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

OrderApp/urls.py
from django.contrib import admin
from django.urls import path

from OrderApp.views import *

app_name = 'OrderApp'

urlpatterns = [
  path('addingcart/<int:id>/', add_to_shoping_cart, name='add_to_shoping_cart'),
  path('cart_details/', cart_detials, name='cart_detials'),
  path('cart_delete/<int:id>/', cart_delete, name='cart_delete'), 
  
  
  

]

Stores/urls.py
from django.conf.urls import url
from django.urls import path

from .views import *

app_name = 'Stores'  # ඕනිම ඇප එකක සිට මෙහි urls වලට ඇමතීම ඉතා පැහදිලිව මෙමගින් කර ගත හැකි වේ. 

urlpatterns = [
    path('',Homeview.home,name="home"),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact_dat'),
    path('product/<slug:slug>',product_single,name="product_single"), 
    path('product/<int:id>/<slug:slug>/', category_product, name='category_product'), 
    path('search/', SearchView.as_view(), name='search'),
    path('add-to-cart',add_to_cart,name='add_to_cart'),
    path('delete-from-cart',delete_cart_item,name='delete-from-cart'),
      
    
] 

Stores/models.py
from django.db import models
from django.forms import EmailInput, ModelForm, TextInput


class Setting(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
    title = models.CharField(max_length=200)
    keyword = models.CharField(max_length=200)
    author = models.CharField(blank=True,max_length=100)
    description = models.TextField()
    robot = models.CharField(blank=True,max_length=200)
    address = models.CharField(max_length=200)
    phoneone = models.IntegerField()
    phonetwo = models.IntegerField()
    fax = models.CharField(blank=True, max_length=50)
    email = models.EmailField(blank=True, null=True, max_length=50)
    smptserver = models.CharField(max_length=100)
    smtpemail = models.EmailField(blank=True, null=True, max_length=50)
    smptpassword = models.CharField(blank=True, max_length=50)
    smptport = models.CharField(blank=True, max_length=100)
    icon = models.ImageField(blank=True, null=True, upload_to='icon/')
    facebook = models.CharField(blank=True, max_length=100)
    instagram = models.CharField(blank=True, max_length=100)
    address = models.TextField()
    contact = models.TextField()
    reference = models.TextField()
    status = models.CharField(max_length=50, choices=STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
    @staticmethod
    def get_settings_by_id(settings_id):
       return Setting.objects.get(id=settings_id)

class ContactMessage(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed', 'Closed'),

    )
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=40)
    subject = models.CharField(max_length=200, blank=True)
    message = models.TextField(max_length=1000, blank=True)
    status = models.CharField(max_length=40, choices=STATUS, default='New')
    ip = models.CharField(max_length=100, blank=True)
    Note = models.CharField(max_length=200, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name



class ContactForm(ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name': TextInput(attrs={'class': 'input', 'placeholder': 'Name & Sure name'}),
            'email': EmailInput(attrs={'class': 'input', 'placeholder': 'Write your email'}),
            'subject': TextInput(attrs={'class': 'input', 'placeholder': 'Wrte your Subjects'}),
            'message': TextInput(attrs={'class': 'input', 'placeholder': 'Write your messages'}),
        } 
   

Stores/forms.py
from django import forms


class SearchForm(forms.Form):
	query = forms.CharField(max_length=200)
	cat_id=forms.IntegerField()

Stores/views.py
from django.contrib import messages
from django.shortcuts import (HttpResponse, HttpResponseRedirect,
                              get_object_or_404, redirect, render)
from django.views import View
from django.views.generic import TemplateView
from django.http import JsonResponse
from django.template.loader import render_to_string
from Marketing.models import ImagesAdds
from Products.models import (Category, Images, MiniCategory, Product,
                             SubCategory)

from .models import *
from .serializers import menuserializer, minimenuserializer, submenuserializer


class Homeview(View):
    
    
    def home(request):
        try:
          
          categories = Category.get_all_categories()
          subcategories = SubCategory.get_all_subcategories()
          minicategories = MiniCategory.get_all_mini_categories()
          
          
          mainmenu = menuserializer(categories,many=True)
          data = mainmenu.data         
          request.session['mainM'] = data
      
          submenudata = submenuserializer(subcategories,many=True)
          subdata = submenudata.data          
          request.session['submenu'] = subdata
          
          minimenudata = minimenuserializer(minicategories,many=True)
          minidata = minimenudata.data          
          request.session['minimenu'] = minidata
                  
          setting = Setting.get_settings_by_id(1)
          top_banners = ImagesAdds.objects.filter(image_category='Top-Banner') # ප්‍රධාන බැනර් එකට පින්තුර දාන්නේ මෙතනින්. මේකට පින්තුර එකතු කරන්නේ  Image adds කියන ටේබල් එකෙන් 
          #slider_products = Product.objects.all().order_by('id')[:3] # පහලම  තිබෙන තුන ලබා ගැනීම. 
          latest_products = Product.products.all().order_by('-id')[:3] # ඉහළම  තිබෙන තුන ලබා ගැනීම. 
          best_seller = Product.products.filter(variant='Best-Seller').order_by('-id')[:5]
          featured_products = Product.products.filter(variant='Featured-Product')
          
          products = None
          categoryID = request.GET.get('category') # href="/?category={{category.id}}" එකෙන් මෙතන CategoeryID එකට ලින්ක් කර අදාළ category id එක ලබා ගනී 
         
          if categoryID == None:
               
               products = Product.get_products_by_categoryID(None)
               
          else:
               products  = Product.get_products_by_categoryID(categoryID)
               
               
                         
          context = {'setting': setting,
                     #'slider_products':slider_products,
                     'latest_products':latest_products,
                     'featured_products':featured_products,
                     'best_seller':best_seller,
                     'top_banners':top_banners,
                     'categories':categories,
                     'subcategories':subcategories,
                     'minicategories':minicategories,
                     'products':products}
          
          return render(request, 'index.html',context)
        except Exception as identifier:         
          return render(request, 'index.html', {}) 
          
     
# About Page
def about(request):
    setting = Setting.get_settings_by_id(1)
    context = {'setting':setting,}
    return render(request, 'about.html', context)   

# Contact Page
def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid(): 
            data = ContactMessage()
            data.name = form.cleaned_data['name']
            data.email = form.cleaned_data['email']
            data.subject = form.cleaned_data['subject']
            data.message = form.cleaned_data['message']
            data.ip = request.META.get('REMOTE_ADDR')
            data.save()
            messages.success(request, 'Profile details updated.')
#
            return redirect('contact_dat')
#
    form = ContactForm
    setting = Setting.get_settings_by_id(1)
    context = {
        'form': form,
        'setting':setting,         
         }
    return render(request, 'contact.html', context)


# search bar
class SearchView(TemplateView):
    template_name = "products_templates/category_products.html"
    def get_context_data(self,**kwargs):
        
        context = super().get_context_data(**kwargs)
        kw = self.request.GET.get("keyword")
        product_cat = Product.objects.filter(title__icontains=kw)
        
        setting = Setting.get_settings_by_id(1)
        context = {
            'product_cat':product_cat,
            'setting':setting,
        }
        #context["product_cat"] = product_cat
        #context["setting"]   = setting
        return context
    
    
# Sngle Product View Class


def product_single(request,slug):
       product = get_object_or_404(Product, slug=slug, in_stock=True)
       setting = Setting.get_settings_by_id(1)
       latest_products = Product.products.filter(category=product.category)
       context = {
           'single_product': product,
           'setting':setting,
           'latest_products':latest_products
           }
       return render(request,'products_templates/single-product.html',context)

# Displya All Products relatete to your selected category
     
def category_product(request, id, slug):
    categories = Category.objects.all()
    subcategories = SubCategory.objects.all()
    minicategories = MiniCategory.objects.all()
          
    
    setting = Setting.objects.get(id=1)
    sliding_images = Product.objects.all().order_by('id')[:2]
    prouct_cat = Product.objects.filter(category_id=id)
    context = {
        'categories': categories,
        'subcategories': subcategories,
        'subcategories': subcategories,        
        'setting': setting,
        'product_cat': prouct_cat,
        'sliding_images': sliding_images,
        'minicategories':minicategories,
    }
    return render(request, 'products_templates/category_products.html', context)


def add_to_cart(request):
    
    #del request.session['cartdata']
	
    cart_p={}
    cart_p[str(request.GET['id'])]={
		'image':request.GET['image'],
		'title':request.GET['title'],
		'qty':request.GET['qty'],
		'price':request.GET['price'],
	}
    if 'cartdata' in request.session: # session එකක් තියෙනව නම් 
        if str(request.GET['id']) in request.session['cartdata']: # select කරපු product එක මේ session එකේ තියෙනවද බලනවා 
            cart_data=request.session['cartdata'] # ඊට පස්සේ මේ session එක  card_data එකට සමාන කරලා 
            cart_data[str(request.GET['id'])]['qty']=int(cart_p[str(request.GET['id'])]['qty']) # මේ product එකේ quantity එක increase කරනවා
            cart_data.update(cart_data) 
            request.session['cartdata']=cart_data
        else:
            cart_data=request.session['cartdata'] # product එක  cart එකේ තිබුනේ නැත්නම්
            cart_data.update(cart_p) # සැම විටම session එක පවතින තත්වයට update කල යුතුමය 
            request.session['cartdata']=cart_data
    else:
        request.session['cartdata']=cart_p # if not session create session 
    return JsonResponse({'data':request.session['cartdata'],'totalitems':len(request.session['cartdata'])})


def delete_cart_item(request):
    p_id=str(request.GET['id']) # ID එක ගන්නවා
    print("in side thte dlete methohd ")
    setting = Setting.objects.get(id=1) 
    if 'cartdata' in request.session:# session එක ගන්නවා 
        if p_id in request.session['cartdata']:# ඉහතින් ගත්ත id එකට අදාල product එක session එකේ  තියෙවනවා නම්
            cart_data=request.session['cartdata']# session එක  card_data එකට දාල
            del request.session['cartdata'][p_id]# ඒ product එක කරලා දානව ඊට පස්සේ
            request.session['cartdata']=cart_data# product එක  remove කරලා  remove කලබවට තොරතුරු නැවැත  session එක updataeකරයි
            
    total_amt=0
    for p_id,item in request.session['cartdata'].items():
        total_amt+=int(item['qty'])*float(item['price'])
        
    t=render_to_string('updated-cart-list.html',{'cart_data':request.session['cartdata'],'totalitems':len(request.session['cartdata']),'total_amt':total_amt})
    return JsonResponse({'data':t,'totalitems':len(request.session['cartdata'])})    
     

Stores/templates/basetemplates/biginslider.html
{% load static %}
 {% load mptt_tags %}

<div class="slider-with-banner">
                <div class="container">
                    <div class="row">
                        <!-- Begin Category Menu Area -->
                        <div class="col-lg-3">
                            <!--Category Menu Start-->
                            <div class="category-menu">
                                <div class="category-heading">
                                    <h2 class="categories-toggle"><span>categories</span></h2>
                                </div>                         
                        <div id="cate-toggle" class="category-menu-list">
                            <ul>                                
                               {% for item in request.session.mainM %}
                                    <li class="right-menu"><a href="{%url 'Stores:category_product' id=item.id slug=item.slug %}">{{ item.title }}</a>
                                        <ul class="cat-mega-menu">
                                            {% for  value in  request.session.submenu %} 
                                            {% if  value.category == item.id %} 
                                                <li class="right-menu cat-mega-title">
                                                    <a href="{%url 'Stores:category_product' id=value.id slug=value.slug %}">{{ value.title }}</a>
                                                        <ul>
                                                             {% for  mini in  request.session.minimenu %} 
                                                                {% if  mini.subcategory == value.id %}
                                                                <li><a href="{%url 'Stores:category_product' id=mini.id slug=mini.slug %}">{{mini.title}}</a></li>
                                                                {% endif %}
                                                             {% endfor %}
                                                        </ul>
                                                </li>
                                             {% endif %}
                                             {% endfor %}  
                                        </ul> 
                                    </li>   
                                {% endfor %}                                     
                            </ul>
                                
                        </div> 
                </div>   


                            <!--Category Menu End-->  
                        </div>
                        <!-- Category Menu Area End Here -->
                        <!-- Begin Slider Area -->
                        <div class="col-lg-9">
                            <div class="slider-area pt-sm-30 pt-xs-30">
                                <div class="slider-active owl-carousel">
                                    <!-- Begin Single Slide Area -->
                                    {% for top_banner in top_banners %}
                                    <div class="single-slide align-center-left animation-style-0{{top_banner.id}} bg-{{top_banner.id}}">
                                        <img src="{{top_banner.ImageUrl}}" alt="placeholder+image">    
                                    <div class="slider-progress"></div>
                                        <div class="slider-content">
                                            <h5>{{top_banner.title}}<span></span> This Week</h5>
                                            <h2>{{top_banner.header}}</h2>
                                            <h3><span>{{top_banner.description}}</span></h3>
                                            <div class="default-btn slide-btn">
                                                <a class="links" href="shop-left-sidebar.html">Shopping Now</a>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                    <!-- Single Slide Area End Here -->                                   
                                    
                                    
                                </div>
                            </div>
                        </div>
                        <!-- Slider Area End Here -->
                    </div>
                </div>
            </div>

Stores/templates/basetemplates/biginslider_in_category_products.html
{% load static %}
{% load mptt_tags %}

            <!-- Begin Slider With Banner Area -->
            <div class="slider-with-banner">
                <div class="container">
                    <div class="row">
                        <!-- Begin Slider Area -->
                        <div class="col-lg-8 col-md-8">
                            <div class="slider-area">
                               <div class="slider-active owl-carousel">
                                    <!-- Begin Single Slide Area -->
                                    {% for p in categories%} 
                                    <!-- Single Slide Area End Here -->
                                    <!-- Begin Single Slide Area -->
                                    <div class="single-slide align-center-left animation-style-0{{p.id}} bg-{{p.id}}">
                                     <img src="{{p.ImageUrl}}" alt="">
                                        <div class="slider-progress"></div>
                                        <div class="slider-content">
                                            <h5>{{p.title}} <span>y</span></h5>
                                            <h2>{{p.detail}}</h2>
                                            <h3>Start Your Shopping Adventure <span></span></h3>
                                            <div class="default-btn slide-btn">
                                                <a class="links" href="shop-left-sidebar.html">Shopping Now</a>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                    <!-- Single Slide Area End Here -->
                                    <!-- Begin Single Slide Area -->
                                    
                                    <!-- Single Slide Area End Here -->
                                </div>
                            </div>
                        </div>
                        <!-- Slider Area End Here -->
                        <!-- Begin Li Banner Area -->
                        <div class="col-lg-4 col-md-4 text-center pt-xs-30">
                            {%for i in sliding_images%}
                            <div class="li-banner">
                                <a href="#">
                                    <img src="{{i.ImageUrl}}" alt="">
                                </a>
                            </div>
                            {%endfor%}
                        </div>
                        <!-- Li Banner Area End Here -->
                    </div>
                </div>
            </div>

Stores/templates/basetemplates/header.html
{% load static %}

<header>
<!-- Begin Header Top Area -->
<div class="header-top">
  <div class="container">
    <div class="row">
      <!-- Begin Header Top Left Area -->
      <div class="col-lg-3 col-md-4">
        <div class="header-top-left">
          <ul class="phone-wrap">
            <li>
              <span>Telephone Enquiry:</span
              ><a href="#">{{setting.phoneone}}</a>
            </li>
          </ul>
        </div>
      </div>
      <!-- Header Top Left Area End Here -->
      <!-- Begin Header Top Right Area -->
      <div class="col-lg-9 col-md-8">
        <div class="header-top-right">
          <ul class="ht-menu">
            <!-- Begin Setting Area -->
            <li>
              <div class="ht-setting-trigger"><span>Login/Register</span></div>
              <div class="setting ht-setting">
                <ul class="ht-setting-list">
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'userprofile' %}">Hello, {{request.user.username}}</a></li>
                <li><a href="{% url 'userprofile' %}">View Account</a></li>
                <li><a href="{% url 'logout' %}">Logout</a></li>
                
                
                {% else %}
                <li><a href="{%url 'login'%}">Login</a></li>
                <li><a href="{%url 'register'%}">Register</a></li>
                {% endif %}
                </ul>
              </div>
            </li>
            <!-- Setting Area End Here -->
            <!-- Begin Currency Area -->
            <li>
              <span class="currency-selector-wrapper">Currency :</span>
              <div class="ht-currency-trigger"><span>USD $</span></div>
              <div class="currency ht-currency">
                <ul class="ht-setting-list">
                  <li><a href="#">EUR €</a></li>
                  <li class="active"><a href="#">USD $</a></li>
                </ul>
              </div>
            </li>
            <!-- Currency Area End Here -->
            <!-- Begin Language Area -->
            <li>
              <span class="language-selector-wrapper">Language :</span>
              <div class="ht-language-trigger">
                <span>English</span>
              </div>
              <div class="language ht-language">
                <ul class="ht-setting-list">
                  <li class="active">
                    <a href="#"
                      ><img
                        src="{% static ''%}images/menu/flag-icon/1.jpg"
                        alt=""
                      />English</a
                    >
                  </li>
                  <li>
                    <a href="#"
                      ><img
                        src="{% static ''%}images/menu/flag-icon/2.jpg"
                        alt=""
                      />Français</a
                    >
                  </li>
                </ul>
              </div>
            </li>
            <!-- Language Area End Here -->
          </ul>
        </div>
      </div>
      <!-- Header Top Right Area End Here -->
    </div>
  </div>
</div>
<!-- Header Top Area End Here -->
<!-- Begin Header Middle Area -->
<div class="header-middle pl-sm-0 pr-sm-0 pl-xs-0 pr-xs-0">
  <div class="container">
    <div class="row">
      <!-- Begin Header Logo Area -->
      <div class="col-lg-3">
        <div class="logo pb-sm-30 pb-xs-30">
          <a href="{%url 'Stores:home'%}">
            <img src="{{static.icon.url}}" alt="" /> 
          </a>
        </div>
      </div>
      <!-- Header Logo Area End Here -->
      <!-- Begin Header Middle Right Area -->
      <div class="col-lg-9 pl-0 ml-sm-15 ml-xs-15">
        <!-- Begin Header Middle Searchbox Area --> 
        <form  class="hm-searchbox" action="/search/" method="GET">
        <input name="keyword" type="text" class="form-control" placeholder="search">
        <button class="li-btn" type="submit"><i class="fa fa-search"></i></button>
        </form>
        <!-- Header Middle Searchbox Area End Here -->
        <!-- Begin Header Middle Right Area -->
        <div class="header-middle-right">
          <ul class="hm-menu">
            <!-- Begin Header Middle Wishlist Area -->
            <li class="hm-wishlist">
              <a href="wishlist.html">
                <span class="cart-item-count wishlist-item-count"
                  >0</span
                >
                <i class="fa fa-heart-o"></i>
              </a>
            </li>
            <!-- Header Middle Wishlist Area End Here -->
            <!-- Begin Header Mini Cart Area -->
            <li class="hm-minicart">
              <div class="hm-minicart-trigger">
                <span class="item-icon"></span>
                <span class="item-text"
                  >£80.00
                  <span id="basket-qty" class="cart-item-count">(<span class="cart-list">{{request.session.cartdata|length}}</span>)</span>
                </span>
              </div>
              <span></span>
              <div class="minicart">
                <ul class="minicart-product-list">
                {% for p in cart_product %}
                  <li>
                    <a
                      href="single-product.html"
                      class="minicart-product-image"
                    >
                      <img
                        src="images/product/small-size/5.jpg"
                        alt="cart products"
                      />
                    </a>
                    <div class="minicart-product-details">
                      <h6>
                        <a href="single-product.html"
                          >{{p.product.title}}</a
                        >
                      </h6>
                      <span>£{{p.product.new_price}} x {{p.quantity}}</span>
                    </div>
                    <button class="close" title="Remove">
                      <i class="fa fa-close"></i>
                    </button>
                  </li>
                  {% endfor %}

                </ul>
                <p class="minicart-total">
                  SUBTOTAL: <span>£{{total_amount}}</span>
                </p>
                <div class="minicart-button">
                  <a href="{%url 'OrderApp:cart_detials'%}"
                    class="li-button li-button-fullwidth li-button-dark"
                  >
                    <span>View Full Cart</span>
                  </a>
                  <a
                    href=""
                    class="li-button li-button-fullwidth"
                  >
                    <span>Checkout</span>
                  </a>
                </div>
              </div>
            </li>
            <!-- Header Mini Cart Area End Here -->
          </ul>
        </div>
        <!-- Header Middle Right Area End Here -->
      </div>
      <!-- Header Middle Right Area End Here -->
    </div>
  </div>
</div>
<!-- Header Middle Area End Here -->
<!-- Begin Header Bottom Area -->
<div class="header-bottom header-sticky d-none d-lg-block d-xl-block">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <!-- Begin Header Bottom Menu Area -->
        <div class="hb-menu">
          <nav>
            <ul>
              <li><a href="{%url 'Stores:home'%}">Home</a></li>
     
              <li><a href="{%url 'Stores:about'%}">About Us</a></li>
              <li><a href="{%url 'Stores:contact_dat'%}">Contact</a></li>
              
            </ul>
          </nav>
        </div>
        <!-- Header Bottom Menu Area End Here -->
      </div>
    </div>
  </div>
</div>
<!-- Header Bottom Area End Here -->
<!-- Begin Mobile Menu Area -->
<div class="mobile-menu-area d-lg-none d-xl-none col-12">
  <div class="container">
    <div class="row">
      <div class="mobile-menu"></div>
    </div>
  </div>
</div>
<!-- Mobile Menu Area End Here -->
</header>

Stores/templates/basetemplates/product_display2.html
{% load static %}
<section
class="
  product-area
  li-laptop-product li-trendding-products
  best-sellers
  pb-45
"
>
<div class="container">
  <div class="row">
    <!-- Begin Li's Section Area -->
    <div class="col-lg-12">
      <div class="li-section-title">
        <h2>
          <span>Bestsellers</span>
        </h2>
      </div>
      <div class="row">
        <div class="product-active owl-carousel">
        {%for p in latest_products%}
          <div class="col-lg-12">
            <!-- single-product-wrap start -->
            <div class="single-product-wrap">
              <div class="product-image">
                
              <a href="{{p.get_absolute_url}}">
              <img
                src="{{p.image.url}}"
                alt="Li's Product Image"
              />
            </a>

                <span class="sticker">New</span>
              </div>
              <div class="product_desc">
                <div class="product_desc_info">
                  <div class="product-review">
                    <h5 class="manufacturer">
                      <a href="shop-left-sidebar.html"
                        >{{p.category}}</a
                      >
                    </h5>
                    <div class="rating-box">
                      <ul class="rating">
                        <li><i class="fa fa-star-o"></i></li>
                        <li><i class="fa fa-star-o"></i></li>
                        <li><i class="fa fa-star-o"></i></li>
                        <li class="no-star">
                          <i class="fa fa-star-o"></i>
                        </li>
                        <li class="no-star">
                          <i class="fa fa-star-o"></i>
                        </li>
                      </ul>
                    </div>
                  </div>
                  <h4>
                    <a class="product_name" href="single-product.html"
                      >{{p.title}}</a
                    >
                  </h4>
                  <div class="price-box">
                    <span class="new-price">${{p.new_price}}</span>
                  </div>
                </div>
                <div class="add-actions">
                  <ul class="add-actions-link">
                    <li class="add-cart active">
                      <a href="{%url 'OrderApp:add_to_shoping_cart' id=p.id %}">Add to cart</a>
                    </li>
                    <li>
                      <a class="links-details" href="wishlist.html"
                        ><i class="fa fa-heart-o"></i
                      ></a>
                    </li>
                    <li>
                      <a
                        href="#"
                        title="quick view"
                        class="quick-view-btn"
                        data-toggle="modal"
                        data-target="#exampleModalCenter"
                        ><i class="fa fa-eye"></i
                      ></a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <!-- single-product-wrap end -->
          </div>
        {% endfor %}
        </div>
      </div>
    </div>
    <!-- Li's Section Area End Here -->
  </div>
</div>
</section>